language: python
sudo: required

services:
  - docker

before_install:
    - wget https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
    - sudo tar -C /usr/local/bin -xzvf docker-squash-linux-amd64-v0.2.0.tar.gz
    - tar --version
    - sudo apt-get update -y -qq
    - sudo apt-get install -o Dpkg::Options::="--force-confnew" -y -qq docker-engine
    - docker -v
install:
    - docker build -f docker/Dockerfile -t openspending/os-data-importers:latest .
script:
    - docker login --username=${DOCKER_HUB_USERNAME} --email=${DOCKER_HUB_EMAIL} --password=${DOCKER_HUB_PASSWORD}
deploy:
    provider: script
    script: docker/deploy.sh
    skip_cleanup: true
    on:
       branch: master

notifications:
  slack:
    secure: TKPyvVSxr6x4BnNAK4j5/sWQhyScalgc13gOX0300TLqOtuw1bRvKm0XrUaK2n32XRzb9ZkOQDJvPo2cumXOYM16343No5NA2ekeDc6ULgtOFta8hY3Txc9ATkvLSnUfRr5mLQ1sknGLKfV2IFDFJiBz9ivMLivpaFR6gn7vcFM=
