version: "3"

services:

  os-data-importers:
    build: '.'
    environment:
      OS_DPP_DISABLE_PIPELINES: 'False'
      DPP_BASE_PATH: "/"
      # DPP_BASIC_AUTH_USERNAME: openspending
      # DPP_BASIC_AUTH_PASSWORD: letmein
      DPP_DB_ENGINE: postgresql://postgres@db/postgres
      ELASTICSEARCH_ADDRESS: es:9200
      OS_ELASTICSEARCH_ADDRESS: es:9200
      OS_API_CACHE: redis
      DPP_REDIS_HOST: redis
      DPP_CELERY_BROKER: redis://redis:6379/10
    ports:
      - "5000:5000"
    volumes:
      - source-specs:/app/source-specs

  repository-agent:
    image: 'openspending/repository-agent:ddd5473'
    environment:
      REPO_AGENT_CLEAN_ON_UPDATE: 'False'
      REPO_AGENT_BASE_DIR: /app/source-specs
      REPO_AGENT_UPDATE_FREQUENCY: 60
      REPO_AGENT_BROKER: redis://redis:6379/11
      REPO_AGENT_REPOS: https://github.com/openspending/os-source-specs#simple
    volumes:
      - source-specs:/app/source-specs

  redis:
    image: 'redis:3.2-alpine'
    expose:
      - 6379
    # ports:
    #   - "6379:6379"

  es:
    image: bitnami/elasticsearch:5.6.4
    expose:
      - 9200
      - 9300
    # ports:
    #   - "9200:9200"

  db:
    image: 'postgres:10-alpine'
    expose:
      - 5432
    # ports:
    #   - "5432:5432"

volumes:
  source-specs:
