sudo:
  false

language:
  python

python:
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install --upgrade -r requirements.dev.txt

script:
  - pylama common
  - python -m pytest --verbose --cov=common tests

after_success:
  - coveralls
